apiVersion: batch/v1
kind: Job
metadata:
  name: k6-executor
spec:
  completions: 3 
  parallelism: 3 
  template:
    metadata:
      labels:
        app: k6-executor
    spec:
      containers:
      - name: k6-executor
        image: joaopaulopmedeiros/k6-executor:latest
        resources:
          limits:
            cpu: "0.5" 
            memory: "512Mi" 
          requests:
            cpu: "0.1"
            memory: "128Mi" 
      restartPolicy: Never   